name: PlasmoVoice
version: ${version}
main: su.plo.voice.paper.PaperVoiceLoader
load: STARTUP
api-version: 1.16
authors: [ Apehum ]
softdepend:
  - PlaceholderAPI
  - LuckPerms
  - PlaceholderAPI
#depend:
#  - kotlin-stdlib
