[host]
ip = "0.0.0.0"
port = 0
# enables proxy mode
proxy_mode = false


[voice]
# Supported sample rates:
# 8000
# 12000
# 24000
# 48000
sample_rate = 48_000

test = false

# Voice distances
distances = [8, 16, 24]

# Default voice distance
# If 0 then distance will be the first element of the distances array
default_distance = 16
max_priority_distance = 0

fade_divisor = 8
priority_fade_divisor = 8

client_mod_required = false
