[versions]
junit5 = "5.8.2"

[libraries]
lombok       = { module = "org.projectlombok:lombok", version = "1.18.24" }
annotations  = { module = "org.jetbrains:annotations", version = "23.0.0" }
guava        = { module = "com.google.guava:guava", version = "31.1-jre" }
gson         = { module = "com.google.code.gson:gson", version = "2.9.0" }
log4j        = { module = "org.apache.logging.log4j:log4j-core", version = "2.17.1" }
junit-api    = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit5" }
junit-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit5" }

[plugins]
architectury-plugin = { id = "architectury-plugin", version = "3.4-SNAPSHOT" }
architectury-loom   = { id = "dev.architectury.loom", version = "0.11.0-SNAPSHOT" }
shadow              = { id = "com.github.johnrengelman.shadow", version = "7.1.0" }
