modLoader="javafml"
loaderVersion="[${loader_version},)"
license="LGPL-3.0"
issueTrackerURL="https://github.com/plasmoapp/plasmo-voice/issues"
[[mods]]
modId="plasmovoice"
version="${version}"
displayName="Plasmo Voice" #mandatory
displayURL="https://github.com/plasmoapp/plasmo-voice"
logoFile="icon.png" #optional
authors="Apehum"
description="A proximity voice chat mod with audio positioning and lots of features"
[[dependencies.plasmovoice]]
    modId="forge"
    mandatory=true
    versionRange="[${forge_version},)"
    ordering="NONE"
    side="BOTH"
[[dependencies.plasmovoice]]
    modId="minecraft"
    mandatory=true
    versionRange="[${minecraft_version}]"
    ordering="NONE"
    side="BOTH"
